### PR TITLE
Lusas_Toolkit: Update to the way Edges are handled and duplication of code

### LINKED ISSUE #354: Lusas_Toolkit: Panels sharing an Edge do not push correctly
#### Description:

The `Lusasid` of the shared edge does not get assigned back to the `Panel` - so it has an id of -1 causing an error.

#### Steps to reproduce:

See test script.

#### Expected behaviour:

`Panel` with shared edges are able to push.

#### Test file(s):

https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/Lusas_Toolkit/%23354%20Panels%20sharing%20an%20Edge%20do%20not%20push%20correctly.gh?csf=1&web=1&e=57fy5M

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### Issues addressed by this PR

Closes #354 

Fixed bug where specific `Panel` objects sharing an `Edge` would not push due to the `Edge` being culled. 

### Test files

https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/Lusas_Toolkit/%23354%20Panels%20sharing%20an%20Edge%20do%20not%20push%20correctly.gh?csf=1&web=1&e=57fy5M

### Changelog

Fixed bug where specific `Panel` objects sharing an `Edge` would not push due to the `Edge` being culled. 

### Additional comments

See https://github.com/BHoM/Lusas_Toolkit/wiki/Lusas-Specific-Adapter-Features#starting-the-adapter for how to start the Adapter. 
You will need to refresh the mesh to view the loads.

### CODE REVIEW

**Review by mriquBH — APPROVED** [review]
I have tested Lusas_Toolkit with test script provided and the bug has been fixed. All elements have been pushed correctly, as well as ID allocation, loading and loading combinations.

I have not reviewed the code.

**Comment by peterjamesnugent** [comment]
@BHoMBot check required

**Review by StephennipBH — APPROVED** [review]
Changes approved. I have carried out additional checks for panels that dont share edges and also panels with more than 3 edges.

**Comment by peterjamesnugent** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check ready-to-merge

**Pull request merged**
