### PR TITLE
Refactor Adapter to work with Lusas170 and Lusas180

### LINKED ISSUE #235: Update Lusas_Adapter to cater for Lusas 18.0
#### Description:

Lusas 18.0 has a new version for the DLL, this requires a new NuGet package that has been created.

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### Issues addressed by this PR

Closes #235 

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/EpMrIgCgVktEq5HfZOxZPPEBnSs4dPayL1rNBt4IefUXVw?e=3EDnLg

### Additional comments

The following build configurations need to be tested:
- [x] Debug17
- [x] Release17
- [x] Debug18
- [x] Release18

I have included a v17 and v18 file to test.

The workflow for starting the adapter should be:
1. Run Lusas Modeller (any version)
2. Cancel the Lusas Modeller Startup dialouge box for opening a file
3. Connect the correct file path to the adapter
4. Run the LusasAdapter

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
@FraserGreenroyd we are changing from NuGet packages to the \lib\ folder used in the Revit_Toolkit. This is because the Lusas.Interop.dll has the same namespace, same filename but just different versions. 

I think there will need to be some changes to CI?

**Comment by FraserGreenroyd** [comment]
Yup probably... given they've all failed!

Can you assign something to me - how soon do you want this PR closed out (so I can prioritise)?

**Comment by peterjamesnugent** [comment]
@FraserGreenroyd would the end of this week be possible? We can do the testing of the functionality in the background.

**Comment by FraserGreenroyd** [comment]
Ok that's great, I'll get that looked at while you test the functionality then :smile:

**Comment by Adamek2192** [comment]
I tested for Lusas Version18 and I was able to to create an adapter, push and pull elements, properties and loads with no issues.

**Comment by JKarasinska** [comment]
@peterjamesnugent, I tested Debug17 and Release17 for Lusas Version17.
I was able to to create an adapter, push and pull elements, properties and loads with no issues.

**Comment by StephennipBH** [comment]
@peterjamesnugent , I tested Debug18 and release18 for Lusas version 18. I managed to push and pull  for both with no issues. It is noted that associated model data and sections csv files might have to be deleted in order to overwrite a new push.

**Pull request merged**
