### PR TITLE
Migrate Convert methods to Adapter, change Engine.Lusas namespace to Adapters.Lusas, add formatting to all documents and implement local versioning

### LINKED ISSUE #236: Migrate all Convert methods to the Adapter
#### Broken rules:

All the convert methods currently sit in the Engine.

#### Suggestions to restore compliance:

Move all Convert methods to the Adapter.

### LINKED ISSUE #239: Change Adapter oM and Engine namespaces to External
#### Broken rules:

We want the menu items for Engine and oM classes defined in **Adapter-Based-Toolkits** (= only Toolkits that contain an Adapter project) into a new category, `Adapters`.

This is mainly to tidy up the menu items, to avoid clutter, and leaving the base Engine methods and classes on the top level.

Currently we have this situation:

What we want is:

#### Suggestions to restore compliance:

This means:
1. **Take note of all changes you will be doing at the following points**.
2. Add the `Adapters` name to the namespace of all your oM and Engine classes.
3. This last point applies only for some Toolkits such as Lusas and Revit in the first picture above. Check if you have:
    - `BH.oM.Adapter.something` have to become `BH.oM.Adapters.something` (note the `s`); 
    - `BH.oM.External.something` have to become `BH.oM.Adapters.something`.
    - `BH.oM.Adapters.something` do not change them.
    - `BH.Engine.Adaper.something` have to become `BH.Engine.Adapters.something` (note the `s`);
    - `BH.Engine.External.something` have to become `BH.oM.Adapters.something`.
    - `BH.Engine.Adapers.something` do not change them.

##### You must take note of what changes you've applied and list them in your PR.
E.g.
- All classes that were originally under `BH.oM.SAP2000` are now into `BH.oM.Adapers.SAP2000`
- All classes that were originally under `BH.Engine.SAP2000` are now into `BH.Engine.Adapers.SAP2000`
- All classes that were originally under `BH.oM.Adapter.SAP2000` are now into `BH.oM.Adapers.SAP2000` (note the `s`) 
- All classes that were originally under `BH.oM.External.SAP2000` (note the `s`) are now in `BH.oM.Adapers.SAP2000`

this will be used to inform the Versioning_Toolkit and make sure we get retro-compatibility for this change.

#### IMPORTANT NOTE
Note that the following **`using`s**:
```cs
using BH.oM.Adapter;
using BH.oM.Adapter.Commands;
```
```cs
using BH.Engine.Adapter;
```
```cs
using BH.Adapter.Modules.Structure
```

are **not to be changed** as they refer to the base Adapter namespace, which is not the subject of the current renaming.

### LINKED ISSUE #247: Add correct headers and formatting to all documents
#### Broken rules:

A lot of the files are missing link breaks, headers e.g.:
```
        /***************************************************/
        /**** Public Methods                            ****/
        /***************************************************/
		
        /***************************************************/
        /**** Private Methods                           ****/
        /***************************************************/

       /***************************************************/
```

#### Suggestions to restore compliance:

Add the appropriate headers and breaks to all files.

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### Issues addressed by this PR

Closes #236 
Closes #239 
Closes #247

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/EjHwiuHBSGpJgmezKPl-UrAB2j6dvBUAkXNDrzl1qDcv9g?e=Zx7Wkw

### Changelog

- Moved methods in `.Lusas` namespace to `.Adapters.Lusas` namespace
- Implemented localised versioning for `Lusas_Engine` stored in `Versioning_32.json`
- Ported all `Convert` methods that use the LPI from `Lusas_Engine` to `Lusas_Adapter`
- Added formatting (i.e. headers, line breaks etc.) to all document files 

### Additional Comments
@calumlockhart-bh when reviewing there are a few things to check:
- Make sure you're on the latest branches for BHoM, BHoM_Engine, BHoM_Adapter, and BHoM_UI
- Make sure you clone the Versioning_Toolkit too
- When you open the `VersioningComponents.gh` all the components on the canvas should work, there should not be any error messages and all constructors should produce objects
- Can you also test a push and pull of the simple truss model in `PushPullTest.cs`, I just want to make sure in the porting of methods and changing of namespaces nothing has fallen through the cracks
- You can check the CreateObject, Compute, Modify and Query components and their respective dropdown lists to see that all the methods fall under the Lusas heading (and not the Adapters heading)
- This will fall under the External heading once it has been fixed in the UI, see https://github.com/BHoM/BHoM_UI/issues/223
- Happy for you to just do a few spot checks on the formatting, it's more for our benefit than anything else

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@peterjamesnugent Would you mind raising a PR on Versioning_Toolkit, covering the changes to Midas and Lusas. Can then either merge that one as is, or wait for others to join in with the external changes if needed.

**Comment by FraserGreenroyd** [comment]
Now the versioning can be done locally on this toolkit, @peterjamesnugent , same as we did on XML_Toolkit? :smile:

**Comment by calumlockhart-bh** [comment]
Versioning works for changing the components to the latest versions. Potential accidental causes of incorrectly identifying modules as older than they are don't appear to lead to infinite looping. Considerations for future updates may include skipping version numbers where applicable. Some cells in JSON files left intentionally blank, may lead to slower processing, shouldn't be a problem at the current stage of development, but worth considering streamlining for the future.

**Comment by peterjamesnugent** [comment]
@calumlockhart-bh please review again, the namespaces have changed from External to Adapter as per: https://github.com/BHoM/BHoM_Adapter/issues/213

It should be a case of just opening the script with the new build of Lusas_Toolkit and BHoM_UI.

**Pull request merged**
