### PR TITLE
Refactor results and add full compliment of results

### LINKED ISSUE #203: Refactor results to work with requests
#### Description:

Refactor results to work with requests to match the existing structural adapters.

### LINKED ISSUE #204: Pull BarStrain and BarStress
#### Description:

Add functionality to pull `BarStrain` and `BarStress`.

### LINKED ISSUE #205: Pull MeshDisplacement, MeshStress and MeshVonMises Results
#### Description:

Add functionality to pull `MeshDisplacement`, `MeshStress` and `MeshVonMises` Results.

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### Issues addressed by this PR

Closes #203 
Closes #204 
Closes #205 

-Refactored reading of results to be consistent with the other structural adapters
-Added functionality for pulling the following results: `BarStrain`, `BarStress`, `MeshDisplacement`, `MeshForce`, `MeshStress`, `MeshVonMises`

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/EjGtEZcmeOJHlpfYyH-vXkMBebWFvaSy5hzI9KVnGVGDEQ?e=C5JEeA

### Changelog

-Refactored reading of results to be consistent with the other structural adapters
-Added functionality for pulling the following results: `BarStrain`, `BarStress`, `MeshDisplacement`, `MeshForce`, `MeshStress`, `MeshVonMises`

### Additional comments

I have created some reports to allow you to easily compare the results in Lusas.
Please read [the section on naming for Lusas features](https://github.com/BHoM/Lusas_Toolkit/wiki/Lusas-Specific-Adapter-Features#elements) and the [section of equivalent objects between the BHoM and Lusas.](https://github.com/BHoM/Lusas_Toolkit/wiki/BHoM-Lusas-Object-Relations#elements)

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
CI does not succeed because Dimensional_oM does has not been merged.

**Comment by peterjamesnugent** [comment]
> Comment was made before the most recent commit for PR 217 in repo BHoM/Lusas_Toolkit

@FraserGreenroyd last commit was made at 15:04, my comment was made at 15:05 - this PR is behaving a bit strangely in general. I had trouble updated my OP too.

**Comment by FraserGreenroyd** [comment]
GitHub has been on a server 500 on and off most of the afternoon @peterjamesnugent - I wonder if that affected what was happening here as both pipelines have just started successfully?

**Comment by peterjamesnugent** [comment]
Something very odd going on here, despite pulling the Feature maximum and Feature minimum they are returning the exact same results (this is for Line 7):
image
image

Extracting results from the model itself shows that there is a difference in the Feature maximum and Feature minimum:
image
image

**Comment by peterjamesnugent** [comment]
The issue was in the getResultsComponents does not actually return "Feature Extreme" when it is requested, instead it returns the results at the internal nodes. Therefore, when using getFeatureResults, the intention was that it would only have one result, so the resultType would not matter . However, now that we know it is giving all the internal results I have added the resultType as a variable and their numbers correspond (from the LPI Documentation):

> 3 = maximum, 4 = minimum, 5 = absolute 6 = extreme

**Comment by peterjamesnugent** [comment]
The Uxx and Uyy are 0 because they are < the tolerance. 

I have made the other two changes.

**Comment by peterjamesnugent** [comment]
This PR could not be rebased due to conflicts, I have therefore raised another PR here #229

**Pull request closed without merging**
