### PR TITLE
Add BHoMAdapter inheritance for LusasV191Adapter

### LINKED ISSUE #362: LusasV191Adapter does not inherit from BHoMAdapter
Resulting in compilation errors in installer checks at the very least...

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #362

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling
@BHoMBot check serialisation

**Review by peterjamesnugent — APPROVED** [review]
Tested each of the adapter (v17, v18, v19, v191 and v20) and happy they all work - pushed a few elements and properties as a quick verification.

**Comment by peterjamesnugent** [comment]
@BHoMBot check versioning 
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: versioning, ready-to-merge

**Pull request merged**
