### PR TITLE
Upgrade Adapter for Lusas v20.0

### LINKED ISSUE #358: Upgrade Adapter for Lusas 20.0
#### Description:

Add functionality for Lusas v20.0.

Refer to https://github.com/BHoM/Lusas_Toolkit/pull/343 for references.

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### Issues addressed by this PR

Closes #358 

### Test files

[Push and pull elements, properties and tags](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/Lusas_Toolkit/%23358%20Upgrade%20adapter%20for%20Lusas%2020/BuroHappold_BHoM_v6.1.beta_Create%20-%20read%20-%20elements%20-%20bridges.gh?csf=1&web=1&e=Ac93ct)
[Push and Pull Loads](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/Lusas_Toolkit/%23358%20Upgrade%20adapter%20for%20Lusas%2020/BuroHappold_BHoM_v6.1.beta_Create%20read%20loads.gh?csf=1&web=1&e=EFFTp8)

### Changelog

Added adapter functionality for Lusas 20.0

### Additional comments

I have tested this on Lusas v20.0-3, but should work for 20.0-0 to 20.0-3.

### CODE REVIEW

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]
Please update the PR title to be appropriate @peterjamesnugent . Also can you add an `altConfigs.txt` file so the bot knows there's multiple configs to check when running checks on this repo.
See an example on [Revit_Toolkit here](https://github.com/BHoM/Revit_Toolkit/blob/develop/altConfigs.txt) 😄

**Comment by peterjamesnugent** [comment]
@BHoMBot check required

**Comment by peterjamesnugent** [comment]
@BHoMBot fix project file ref. 14679014685

**Comment by peterjamesnugent** [comment]
@BHoMBot check required

**Review by StephennipBH — CHANGES_REQUESTED** [review]
Please see below screenshot for the question on mesh setting 2d split 2d size
image

**Comment by peterjamesnugent** [comment]
@StephennipBH that was an issue with the script, the length parameters was not plugged in to the right input. I have updated the script and tested:
image

**Review by StephennipBH — APPROVED** [review]
Noted that it's a small error in the test script rather than component functionality, therefore approved

**Comment by peterjamesnugent** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check ready-to-merge

**Pull request merged**
