### PR TITLE
Update the dependency type for LoadCombination

### LINKED ISSUE #331: Add dependency type for LoadCombination on Loadcases using recent BHoM_Adapter updates
#### Description:

Allow `Loadcase` and `LoadCombination` to be pushed to Lusas in one go using the dependency types.

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### Issues addressed by this PR

Closes #331

### Test files

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/Lusas_Toolkit/%23332-AddLoadCombinationDependencyType?csf=1&web=1&e=sP0QgZ

### Changelog

- Update the DependencyTypes for `LoadCombination` to include `Loadcase`

### CODE REVIEW

**Review by calumlockhart-bh — APPROVED** [review]
Works as intended.

**Comment by peterjamesnugent** [comment]
@BHoMBot check required

**Comment by peterjamesnugent** [comment]
@BHoMBot 
check copyright compliance
check ready-to-merge

**Comment by peterjamesnugent** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check ready-to-merge

**Pull request merged**
