### PR TITLE
Add additional Execute commands 

### LINKED ISSUE #320: SaveBeforeClose execute action to be added
#### Description:

Implement `SaveBeforeClose` action.

### LINKED ISSUE #327: Add Exit command functionality
#### Description:

Implement Exit command functionality

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### NOTE: Depends on 

https://github.com/BHoM/BHoM_Adapter/pull/303
   
### Issues addressed by this PR

Closes #320 
Closes #327 

### Test files

https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/Lusas_Toolkit/%23328-AddAdditionalExecuteCommands/AdditionalExecuteCommands.gh?csf=1&web=1&e=UAPWbD

### Changelog

- Added `Exit` command functionality
- Modified `Close` command functionality to take in to account `SaveBeforeClose` input

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
@BHoMBot check compliance

**Review by StephennipBH — COMMENTED** [review]
I have checked all the components on the test script. They all work as intended. However, I have added a check on "false to SaveBeforeClose Close command", am I suppose to get an error message for that as well ?

**Comment by peterjamesnugent** [comment]
@StephennipBH no - if `SaveBeforeClose` is `false`, then the application will just quit so no error will be raised.

The issue comes when it is set to `true` and the model has never been saved before.

**Review by StephennipBH — APPROVED** [review]
Changes work as intended, changes approved.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
