### PR TITLE
Remove use of NextFreeID and let Lusas dictate Ids for elements, properties and loads

### LINKED ISSUE #259: Remove use of NextFreeID and let Lusas choose the ID

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### Issues addressed by this PR

Closes #259 

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/Etm7b2UKaOpMiS_rxlK-8acB0O8Vz4qoKIYIuNxRkVug5w?e=vxx1ee

### Changelog

- Removed use of `NextFreeId` to allow Lusas to dictate the next available Id for an object
- Removed storing of `AdapterIdName` in names for element, properties and loads e.g. P1, L1, S1 etc.
-  Added functionality to read `MeshSettings2D` when pulling `Panel`s

### Additional comments

There are three different aspects to test:
- Create/Read of elements
- Create/Read of loads
- Read results

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
@FraserGreenroyd An odd failure from the CI check, if I follow the fix suggested it will break the link to the Structure_AdaptersModule.dll:
image

I built the latest BHoM_Adapter from master and as far as I am aware the .dll has no changed:
image

@alelom are you aware of any changes to the BHoM_Adapter or CI?

**Comment by FraserGreenroyd** [comment]
Looks like an issue with the CI, I'm happy to say this pr could be merged with that failing if it becomes ready to merge before I can look at test toolkit. Can you raise an issue for when I'm back!

**Pull request merged**
