### PR TITLE
Upgrade to Lusas v21.1

### LINKED ISSUE #409: Check minor version update Lusas 21.1-0

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### Issues addressed by this PR

Closes #409 

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/EvlUJAd76v1Ej7qKRWMeL7IBt-vZbuG4bLWsHP6tNtwosA?e=y6HxxA

### Changelog

- Added `LusasAdapterV2111` for v21.1

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
@BHoMBot check installer

**Comment by peterjamesnugent** [comment]
@BHoMBot check installer

**Comment by peterjamesnugent** [comment]
@BHoMBot check installer

**Review by JacobYoules — COMMENTED** [review]
Tried pushing panels with support properties. These did not remain once the panels were pulled. Please see: https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/Lusas_Toolkit/%23410%20Wall%20Support%20Bug.gh?csf=1&web=1&e=mf7N18

**Comment by peterjamesnugent** [comment]
@BHoMBot check installer

**Review by JacobYoules — COMMENTED** [review]
Checked and found edge supports have been pulled correctly

**Review by JacobYoules — COMMENTED** [review]
I have checked the following:
1. Checked adapter has established connection with software
2. Checked push/pull of elements (nodes, bars, panels)
3. Checked push/pull of properties (sections properties, releases, supports)
4. Checked push/push of loads (node loading, bar loading, panel loading)
5. Checked pull of results (displacement, reaction, force, stresses for bar, node and panel)

**Comment by peterjamesnugent** [comment]
@BHoMBot check versioning

**Comment by peterjamesnugent** [comment]
@BHoMBot check versioning

**Review by JacobYoules — APPROVED** [review]

**Review by JacobYoules — APPROVED** [review]
Happy to approve based on previous review

**Comment by peterjamesnugent** [comment]
@BHoMBot check versioning

**Comment by peterjamesnugent** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
