### PR TITLE
Add null checks to prevent Lusas_Toolkit from crashing

### LINKED ISSUE #290: Add null checks where possible to prevent Push/Pull from crashing
#### Description:

Reduce the amount of times that the Push/Pull components crash - as a fall back return a null in place of an object and raise an error for elements and warning for properties/loads.

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### Issues addressed by this PR

Closes #290 

### Test files

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/Archive/Lusas_Toolkit/Lusas_Toolkit-%23290?csf=1&web=1&e=BqNuFo

### Changelog

- Add a number of `null` checks for `Node`, `Bar` and `Panel` so that Lusas_Toolkit does not crash

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
@BHoMBot check all

**Comment by peterjamesnugent** [comment]
@BHoMBot check all

**Comment by peterjamesnugent** [comment]
@BHoMBot check all

**Comment by peterjamesnugent** [comment]
@BHoMBot check check-project-compliance check code-compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check check-project-compliance check code-compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check code-compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check-code-compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check-code-compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check all

**Comment by peterjamesnugent** [comment]
@BHoMBot check all

**Comment by peterjamesnugent** [comment]
@BHoMBot check-code-compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check all

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright compliance

**Review by StephennipBH — CHANGES_REQUESTED** [review]
The following have been highlighted:
- Nurbs and eliptical openings panel:
It crashes when you put a property into the test but it would be useful to have an error message for invalid edges as Nurbs and eliptical openings cannot be pushed with or without property
- Simple Non-planar panel:
It crashes when you put a property into the test but it would be useful to have an error message for invalid curve as non-planar panel cannot be pushed with or without property
-Bar with null nodes
No warning message about nothing is pushed
-Bar with nodes with null position
Would it be useful to have the warning message as "position is null" instead of "a property of type point being null"
-Bar release null
Would it be easier to understand to specifically say in the warning that "the release condition being null" instead of "a type of ISectionProperty"
- Offset null
No warning message
-Bar section property null
No warning or error message on GH- (two nodes are pushed)
-bar section material null
No warning or error message on GH- (two nodes are pushed)
-bar with support null name
No warning or error message on GH- (two nodes are pushed and a support named ffff)
-concrete section with null material
No warning message
-Generic section for isotropic and orthotropic material crashes due to interpolation order.

**Comment by peterjamesnugent** [comment]
Notes following discussion with @StephennipBH 

> The following have been highlighted:
> - Nurbs and eliptical openings panel:
> It crashes when you put a property into the test but it would be useful to have an error message for "invalid edges" as Nurbs and eliptical openings cannot be pushed with or without property

Add check for `Openings` when there are no `Mesh2DSettings`

> - Simple Non-planar panel:
> It crashes when you put a property into the test but it would be useful to have an error message for "invalid curve" as non-planar panel cannot be pushed with or without property

Check `Panel.Geometry()` for planarity. 

> - Bar with null nodes
> No warning message about nothing is pushed

To be checked.

> - Bar with nodes with null position
> Would it be useful to have the warning message as "position is null" instead of "a property of type point being null"

Generic error message.

> - Bar release null
> Would it be easier to understand to specifically say in the warning that "the release condition being null" instead of "a type of ISectionProperty"

As above.

> - Offset null
> No warning message

No offsets used in Lusas - add message that Offsets are not supported.

> - Bar section property null
> No warning or error message on GH- (two nodes are pushed)
> - bar section material null
> No warning or error message on GH- (two nodes are pushed)
> - bar with support null name
> No warning or error message on GH- (two nodes and a support named ffff are pushed)

Make sure Bar is still pushed if properties are `null`.

> - concrete section with null material
> No warning message

To be checked.

> - Generic section for isotropic and orthotropic material crashes due to interpolation order.

To be checked.

**Comment by calumlockhart-bh** [comment]
image

"Panel from wrong discipline" failing to register an error.

"Valid panels made up of lines and arcs..." failing to register true or false due to an error in the code as "16" is not the name of an existing material.

**Comment by FraserGreenroyd** [comment]
> "Panel from wrong discipline" failing to register an error.

Environments Panels are superior anyway 😝

**Comment by peterjamesnugent** [comment]
@calumlockhart-bh both of the comments you raised should be fixed - please re-review.

**Comment by peterjamesnugent** [comment]
@BHoMBot check compliance

**Comment by peterjamesnugent** [comment]
@FraserGreenroyd the IsExtensionMethod is failing on some equality comparers, but they're not part of the `query`, `convert` or `modify` classes so are outside the scope of the compliance check.

**Review by calumlockhart-bh — CHANGES_REQUESTED** [review]
image

The runtimes are slow, I notice you are doing a lot functions with the panels in lines 294 to 333.  If the panel is invalid some of these could be moved to after the validity checks have been carried out to avoid using functions unnecessarily and simply skip over them.

**Comment by peterjamesnugent** [comment]
@calumlockhart-bh I've modififed the code so that the checks are only carried out once - please see comparison below. There is no significant difference between the master branch and this PR branch. 

There is an open issue #316 for revisiting how the `Panels` are created and to look in to how we cna do it quicker with the tools we now have available.

Master branch:
image

PR branch:
image

**Comment by peterjamesnugent** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 2435975499

**Review by StephennipBH — CHANGES_REQUESTED** [review]
Number of comments:  

For panels:
image

These null material have a warning of having an opening when it doesn’t contain any opening. 
 
For Bars:

Null bar and Null nodes don't have any warning:
image
The bars shown in below all have numerous null properties in their section properties and are not pushed to Lusas. Is this intended?
image

**Review by StephennipBH — CHANGES_REQUESTED** [review]
The previous comments have been addressed. 

I would just like to check if this issue should be addressed under this PR, For non-planar panels, although the panels are not pushed but the lines are still pushed to Lusas. I believe it's the order of when the `isPlanar` check took place that leads to this issue.

image

The rest looks good to me.

**Review by calumlockhart-bh — APPROVED** [review]
Some minor differences with formatting within the same code block, is fine but not best practice. Otherwise looks good.

**Comment by peterjamesnugent** [comment]
@StephennipBH Thanks! That's because the `Edge` is a dependency of a `Panel` so all `Edge` objects get pushed first (assuming they pass the null checks). This allows us to eliminate duplicates using comparers when pushing a `List<Panel>`.

@calumlockhart-bh Thanks!

**Review by StephennipBH — APPROVED** [review]

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Comment by peterjamesnugent** [comment]
@FraserGreenroyd code compliance: The IsExtensionMethod is failing on some equality comparers, but they're not part of the query, convert or modify classes so are outside the scope of the compliance check. Your dispensation must have been dismissed following further commits.

The null handling check is comparing to nothing but all the errors/warnings are not associated with this toolkit.

**Comment by peterjamesnugent** [comment]
@BHoMBot check null-handling

**Comment by peterjamesnugent** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 2556198683

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Pull request merged**
