### PR TITLE
Add various AdapterActions

### LINKED ISSUE #291: Add AdapterActions such as ExectuteNewModel, CloseModel etc.

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### Issues addressed by this PR

Closes #291 

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/EgrOhykBy8ZLm9Tj6upF2ykB3ewm0fpMhT9SHFsUchafkg?e=1XMsm5

### Changelog

- Added the following `AdapterActions` `NewModel`, `Save`, `SaveAs`, `Open`, `Analyse`, `AnalyseLoadcases`, `ClearResults`
- Note if there deactivated `Loadcases` when `Analyse` is run, the GUI will show it as deactivated but still have results to display (this is an issue with the Lusas GUI)

### Additional comments

- I have setup the script to be run sequentially to test the different methods
- Feel free to try different combinations (e.g. `NewModel` then `Analyse` without using `SaveAs` first

### CODE REVIEW

**Review by StephennipBH — APPROVED** [review]
The changes work as intended. Changes approved.

**Comment by peterjamesnugent** [comment]
@BHoMBot check code compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check documentation compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check project compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check installer

**Pull request merged**
